version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations opposeek; python manage.py migrate; python manage.py collectstatic --no-input; gunicorn server.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=!!f1r=78mf)an7i&t8yqy*#e%*wwcx59am^8(xor#11uh^98kt
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,192.168.1.104
      - SERPER_API_KEY=
      - OPENAI_API_KEY=