services:
  - type: web
    name: opposeek
    env: python
    repo: https://github.com/KnowYourLines/opposeek.git
    region: ohio
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt; python manage.py makemigrations opposeek; python manage.py migrate; python manage.py collectstatic --no-input"
    startCommand: "gunicorn server.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: opposeek-db
          property: connectionString

databases:
  - name: opposeek-db
    plan: free
    region: ohio
    postgresMajorVersion: 14
    ipAllowList: [] # only allow internal connections
